config/routes.rb
Rails.application.routes.draw do
  get 'home/lugares' => 'home#lugares'
  get 'home/tienda' => 'home#tienda'
  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks"

  }
  root 'home#index'
  get 'home/index' => 'home#index'
    get 'home/registro' => 'home#registro'
    
    #mandar perticion a facebook
    #retorna a nuestra app callback_url
    #Procesar info de facebook
    #Autenticar o crear nuevo usuario
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  			:registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable,
         :omniauthable,
         :omniauth_providers => [:facebook]  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout '_base'
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout '_base'
  def index

  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controller_helper.rb
module ControllerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/index.html.erb
<% content_for :features, "landing-page" %>
<% content_for :class, "landing-page" %>

<div class="wrapper">
	<!--header-filter-->
	<div class="header " style="background-image: url(<%= asset_path 'BARW.png' %>); ">
		
		</div>
	</div>
	<div class="main main-raised">
		<div class="container">
		<div class="row ">
		<div class="col-md-12" style="background-color: darkslategrey;">
			<br><br>
		</div>
				<div class="col-md-12" >
					<div class="col-md-6">
						
						<h2>Experimenta la nueva forma de vivir de noche.</h2>
					</div>
					<div class="col-md-6 align-items-end" style="text-align: right; "">
					<br>
					<br>
					<%= link_to(raw(("<i class='fa fa-diamond' style='font-size:16px;'></i>") + (' Registrarse')), new_user_registration_path, class:"btn btn-danger btn-raised btn-lg" )  %>  
					</div>
					
				</div>
			<div class="section text-center section-landing">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<h1 class="title" style="color: currentColor;">.BAR</h1>
						<h5 class="description">Dolores Hidalgo Cuna de la Independencia Nacional, es uno de los 46 municipios del estado mexicano de Guanajuato. Se ubica en la región norte-centro de su territorio y tiene una extensión de 1656,18 km². De acuerdo con el censo del año 2010, la población asciende a 148.173 a nivel municipal y a 59.240 en la cabecera municipal.</h5>
					</div>
				</div>
				<div class="features">
					<div class="row">
						<div class="col-md-4">
							<div class="feature feature-primary">
								<i class="material-icons">chat</i>
								<h4 class="title">Fácil</h4>
								<p class="description">Esté Sitio es facíl de navergar, ademas  cuenta con información sobre Bares de mayor popularidad en Dolores Hidalgo</p>
							</div>
						</div>
						<div class="col-md-4">
							<div class="feature feature-success">
								<i class="material-icons">verified_user</i>
								<h4 class="title">Seguro</h4>
								<p class="description">Es sitio brinda seguridad y confidencialidad de tus datos</p>
							</div>
						</div>
						<div class="col-md-4">
							<div class="feature feature-danger">
								<i class="material-icons">fingerprint</i>
								<h4 class="title">Redes Sociales</h4>
								<p class="description">Aquí podras autentificarte con las diferentes redes sociales que ya conoces!!</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="section text-center">
				<h2 class="title">Nuestro Equipo</h2>
				<div class="team">
					<div class="row">
						<div class="col-md-4">
							<div class="team-player">
								<%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/13710030_1129312730460225_8147772292064943555_n.jpg?oh=def0df09997e9ed3de921b81fe446f3f&oe=5A334C41
", alt: "Thumbnail Image", class: "img-raised img-circle") %>
								<h4 class="title">Erika Cabrera <br />
								<small class="text-muted">Líder/Documentadora</small>
								</h4>
								<p class="description"><a href="#">links</a> para que las personas puedan seguirlos fuera del sitio.</p>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-twitter"></i></a>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-instagram"></i></a>
								<a href="#pablo" class="btn btn-just-icon btn-default"><i class="fa fa-facebook-square"></i></a>
							</div>
						</div>
						<div class="col-md-4">
							<div class="team-player">
								<%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/14212651_295521587489083_5110215735733400895_n.jpg?oh=ee9bb4dc70ea494fc08c88bf9653855c&oe=5A36AD16", class: "img-raised img-circle") %>
								<h4 class="title">Daniel Guzmán<br />
								<small class="text-muted">Dieseñador/Desarrollador</small>
								</h4>
								<p class="description"><a href="#">links</a>para que las personas puedan seguirlos fuera del sitio.</p>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-twitter"></i></a>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
						<div class="col-md-4">
							<div class="team-player">
								<%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/13686744_1481680908524143_922781301110142229_n.jpg?oh=cd90219037a2ef7ca1c973a347e98733&oe=5A2EA2BF
", alt: "Thumbnail Image", class: "img-raised img-circle") %>
								<h4 class="title">Gabriel Carrillo<br />
								<small class="text-muted">Desarrollador</small>
								</h4>
								<p><a href="#">links</a> para que las personas puedan seguirlos fuera del sitio.</p>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-google-plus"></i></a>
								<a href="#pablo" class="btn btn-just-icon"><i class="fa fa-youtube-play"></i></a>
								<a href="#pablo" class="btn btn-just-icon btn-default"><i class="fa fa-twitter"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<h2 class="text-center title">Trabaja con nosotros</h2>
						<h4 class="text-center description">Envíanos un mensaje, te responderemos enseguida</h4>
						<form class="contact-form">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Tu Nombre</label>
										<input type="email" class="form-control">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Tu Email</label>
										<input type="email" class="form-control">
									</div>
								</div>
							</div>
							<div class="form-group label-floating">
								<label class="control-label">Tu Mensaje</label>
								<textarea class="form-control" rows="4"></textarea>
							</div>
							<div class="row">
								<div class="col-md-4 col-md-offset-4 text-center">
									<button class="btn btn-primary btn-raised">
									Enviar	
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer class="footer">
		<div class="container">
			<nav class="pull-left">
				<ul>
					<li>
						<a href="http://www.creative-tim.com">
							Creative Tim
						</a>
					</li>
					<li>
						<a href="http://presentation.creative-tim.com">
							About Us
						</a>
					</li>
					<li>
						<a href="http://blog.creative-tim.com">
							Blog
						</a>
					</li>
					<li>
						<a href="http://www.creative-tim.com/license">
							Licenses
						</a>
					</li>
				</ul>
			</nav>
			<div class="copyright pull-right">
				&copy; 2017, made with <i class="fa fa-heart heart"></i> by Beernini
			</div>
		</div>
	</footer>
</div>

app/views/home/lugares.html.erb
<% content_for :features, "landing-page" %>
<% content_for :class, "landing-page" %>
<% if user_signed_in? %>
<div class="wrapper">
  <div class="header " style="background-image: url(<%= asset_path 'BARW.png' %>); background-size: cover; background-position: top center;">
  </div>
</div>

<div class="main main-raised">
    <div class="container">
      <div class="row ">
      <div class="col-md-12" style="background-color: darkslategrey;">
        <br><br>
      </div>
    </div>
      <div class="description text-center">
        <p></p>
      </div>
      <div class="row">
      <!--Aqui removí la clase col-md-offset-3 para que no quitara 3 -->
        <div class="col-md-12 ">
          <div class="profile-tabs">
          <!--En la siguiente linea se centra todo lo que va en los tabs-->
            <div class="nav-align-center">
              <ul class="nav nav-pills" role="tablist">
                <!-- AQUI SE ACCIONA LA SELECCION EN LA CLASE ACTIVE-->
                <li class="active">
                  <a href="https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/1476349_311431749052325_3137493258386112318_n.jpg?oh=4cb2e238e79e9fcb8f80e6326d3fdc3e&oe=5A18804B" role="tab" data-toggle="tab">
                    <i class="fa fa-beer" style="font-size:36px"></i>
                    Mama Dolores
                  </a>
                </li>
                <li>
                  <a href="#lap" role="tab" data-toggle="tab">
                    <i class="fa fa-beer" style="font-size:36px"></i>
                    La Pisteria
                  </a>
                </li>
                <li>
                  <a href="https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/14102568_1065011950273645_9172711180421649976_n.png?oh=b7cfc30509326a1cfb0e4e7edc8b2b68&oe=59EAC12B" role="tab" data-toggle="tab">
                    <i class="fa fa-beer" style="font-size:36px"></i>
                    La Terraza
                  </a>
                </li>
                <li>
                  <a href="#alagua" role="tab" data-toggle="tab">
                    <i class="fa fa-beer" style="font-size:36px"></i>
                    Alagua lola
                  </a>
                </li>
                <li>
                  <a href="https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/20727979_1294624873996473_6613319858604456575_n.jpg?oh=4b2c722b897e9fd49c40aa1c49231392&oe=5A2E374A" role="tab" data-toggle="tab">
                    <i class="fa fa-beer" style="font-size:36px"></i>
                    Tercer Piso/Mil Amores
                  </a>
                </li>
              </ul>
              <div class="tab-content gallery">
                <!-- AQUI SE ACCIONA LA SELECCION EN LA CLASE ACTIVE-->
                <div class="tab-pane active" id="mamadolores">
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3" style="text-align: -webkit-center;">
                      <%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/1476349_311431749052325_3137493258386112318_n.jpg?oh=4cb2e238e79e9fcb8f80e6326d3fdc3e&oe=5A18804B", class: "img-circle img-raised img-responsive") %>
                      
                    </div>
                    <div class="col-md-6 col-md-offset-3">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.8623120412058!2d-100.93733498561052!3d21.157877085928543!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b3f0781559837%3A0xd8666049750ef09d!2sMam%C3%A1+Dolores!5e0!3m2!1ses-419!2smx!4v1502907211837" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                  </div>
                </div>
                <div class="tab-pane text-center" id="lap">
                  <div class="row">
                    <div class="col-md-6 " style="text-align: -webkit-center;">
                      <%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/17155690_1357767581005338_3843221641445128931_n.jpg?oh=c01053dfcb80f3cf7783093bbe3e1c3c&oe=5A30D796", class: "img-circle img-raised img-responsive") %>
                      <br>
                    </div>
                    <div class="col-md-6 ">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.8933367114037!2d-100.92337738558098!3d21.15664268877739!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b3f1a7c34940f%3A0xfecc6f44ae71b5f4!2sLa+Pisteria!5e0!3m2!1ses!2smx!4v1502921112250" width="100%" height="450" frameborder="0" style="border-radius:7px; margin-top: 10%;" allowfullscreen></iframe>
                    </div>
                  </div>
                </div>
                <div class="tab-pane text-center" id="laterraza">
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3" style="text-align: -webkit-center;">
                      <%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/14102568_1065011950273645_9172711180421649976_n.png?oh=b7cfc30509326a1cfb0e4e7edc8b2b68&oe=59EAC12B", class: "img-circle img-raised img-responsive") %>
                    </div>
                    <div class="col-md-6 col-md-offset-3">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.867813810636!2d-100.93552338558095!3d21.15765818874244!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b3f07affac7ef%3A0xf98cf1ec81eee7d8!2sLa+Terraza!5e0!3m2!1ses!2smx!4v1502921162343" width="100%" height="450" frameborder="0" style="border-radius:7px; margin-top: 10%;" allowfullscreen></iframe>
                    </div>
                  </div>
                </div>
                <div class="tab-pane text-center" id="alagua">
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3" style="text-align: -webkit-center;">
                      <%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/19748404_1044074665695524_5489625202988233002_n.jpg?oh=2aaed249c7f7fcd50cfa9e2ad1abfb12&oe=5A30AE94", class: "img-circle img-raised img-responsive") %>
                    </div>
                    <div class="col-md-6 col-md-offset-3">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.9062975242896!2d-100.92290428558094!3d21.156126988794984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b3f1a7e80cc07%3A0x544e00a626c06292!2sAL+AGUA+LOLA!5e0!3m2!1ses!2smx!4v1502921270820" width="100%" height="450" frameborder="0" style="border-radius:7px; margin-top: 10%;" allowfullscreen></iframe>
                    </div>
                  </div>
                </div>
                <div class="tab-pane text-center" id="tercer">
                  <div class="row">
                    <div class="col-md-6 " style="text-align: -webkit-center;">
                      <%= image_tag("https://scontent.fpbc1-1.fna.fbcdn.net/v/t1.0-9/20727979_1294624873996473_6613319858604456575_n.jpg?oh=4b2c722b897e9fd49c40aa1c49231392&oe=5A2E374A", class: "img-circle img-raised img-responsive") %>
                      <br>
                    </div>
                    <div class="col-md-6 ">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d586.0021599938547!2d-100.91906867243593!3d21.157103493441646!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x40cc8dcd969c1eff!2sMezcaleria+-+El+MIL+AMORES+-+Desmadre+Bar!5e0!3m2!1ses!2smx!4v1502990845368" width="100%" height="450" frameborder="0" style="border-radius:7px; margin-top: 7%" allowfullscreen></iframe>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>
          <!-- End Profile Tabs -->
        </div>
      </div>
    </div>
</div>
</div>
<footer class="footer">
<div class="container">
  <nav class="pull-left">
    <ul>
      <li>
        <a href="http://www.creative-tim.com">
          Creative Tim
        </a>
      </li>
      <li>
        <a href="http://presentation.creative-tim.com">
          About Us
        </a>
      </li>
      <li>
        <a href="http://blog.creative-tim.com">
          Blog
        </a>
      </li>
      <li>
        <a href="http://www.creative-tim.com/license">
          Licenses
        </a>
      </li>
    </ul>
  </nav>
  <div class="copyright pull-right">
    &copy; 2017, made with <i class="fa fa-heart heart"></i> by Beernini
  </div>
</div>
</footer>
<% else %>
  <div class="header " style="background-image: url(<%= asset_path 'BARW.png' %>); background-size: cover; background-position: top center;">
  </div>
</div>
<div class="main main-raised">
  <div class="container">
    <div class="row ">
      <div class="col-md-12" style="background-color: darkslategrey;">
        <br><br>
      </div>
    </div>
    <div class="col-md-12">
      <h3>Por favor, regístrate para ver esta sección</h3>
    </div>
<% end %>

app/views/home/registro.html.erb
<% content_for :features, "signup-page" %>
<% content_for :class, "signup-page" %>

<nav class="navbar navbar-transparent navbar-absolute">
		<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="http://www.creative-tim.com">Creative Tim</a>
				</div>

				<div class="collapse navbar-collapse" id="navigation-example">
					<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="../components-documentation.html" class="btn" target="_blank">
							Components
						</a>
					</li>
					<li>
						<a href="http://www.creative-tim.com/product/material-kit" target="_blank" class="btn">
													Download
						</a>
					</li>
							<li>
									<a href="https://twitter.com/CreativeTim" target="_blank" class="btn btn-simple">
						<i class="fa fa-twitter"></i>
					</a>
							</li>
							<li>
									<a href="https://www.facebook.com/CreativeTim" target="_blank" class="btn btn-simple">
						<i class="fa fa-facebook-square"></i>
					</a>
							</li>
				<li>
									<a href="https://www.instagram.com/CreativeTimOfficial" target="_blank" class="btn btn-simple">
						<i class="fa fa-instagram"></i>
					</a>
							</li>
					</ul>
				</div>
		</div>
	</nav>

	<div class="wrapper">
	<div class="header header-filter" style="background-image: url(<%= asset_path 'BARW.png' %>); background-size: cover; background-position: top center;">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
					<div class="card card-signup">
						<form class="form" method="" action="">
							<div class="header header-primary text-center">
								<h4>Sign Up</h4>
								<div class="social-line">
									<a href="#pablo" class="btn btn-just-icon">
										<i class="fa fa-facebook-square"></i>
									</a>
									<a href="#pablo" class="btn btn-just-icon">
										<i class="fa fa-twitter"></i>
									</a>
									<a href="#pablo" class="btn btn-just-icon">
										<i class="fa fa-google-plus"></i>
									</a>
								</div>
							</div>
							<p class="text-divider">Or Be Classical</p>
							<div class="content">

								<div class="input-group">
									<span class="input-group-addon">
										<i class="material-icons">face</i>
									</span>
									<input type="text" class="form-control" placeholder="First Name...">
								</div>

								<div class="input-group">
									<span class="input-group-addon">
										<i class="material-icons">email</i>
									</span>
									<input type="text" class="form-control" placeholder="Email...">
								</div>

								<div class="input-group">
									<span class="input-group-addon">
										<i class="material-icons">lock_outline</i>
									</span>
									<input type="password" placeholder="Password..." class="form-control" />
								</div>

								<!-- If you want to add a checkbox to this form, uncomment this code

								<div class="checkbox">
									<label>
										<input type="checkbox" name="optionsCheckboxes" checked>
										Subscribe to newsletter
									</label>
								</div> -->
							</div>
							<div class="footer text-center">
								<a href="#pablo" class="btn btn-primary btn-wd btn-lg">Get Started</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<footer class="footer">
					<div class="container">
							<nav class="pull-left">
					<ul>
						<li>
							<a href="http://www.creative-tim.com">
								Creative Tim
							</a>
						</li>
						<li>
							<a href="http://presentation.creative-tim.com">
								 About Us
							</a>
						</li>
						<li>
							<a href="http://blog.creative-tim.com">
								 Blog
							</a>
						</li>
						<li>
							<a href="http://www.creative-tim.com/license">
								Licenses
							</a>
						</li>
					</ul>
							</nav>
							<div class="copyright pull-right">
									&copy; 2016, made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com" target="_blank">Creative Tim</a>
							</div>
					</div>
			</footer>

	</div>

	</div>

app/views/layouts/_base.html.erb
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="<%= asset_path 'bar.ico' %>">
    <%= csrf_meta_tags %>
    <title>.BAR</title>
    
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,500,700' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :head %>
  </head>
  <body class="<%= yield :class %>" data-features="<%= yield :features %>" style="margin: 0;">
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="notice"><%= alert %></p>
    <% end %>
    <!-----------------BARRA DE NAVEGACION DE TODO EL SITIO-->
    <nav class="navbar navbar-transparent navbar-absolute" style="background-color: rgba(0, 0, 0, 0.4);">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          
          <!--Icono de la barra de navegacion-->
          
          <%= link_to home_index_path do %>
          <div class='logo-container'>
            <div class='logo'>
              <%= image_tag('bar.ico') %>
            </div>
            <div class='brand' style='font-size: large;'>
              .BAR
            </div>
          </div>
          <% end %>
          
          <!--zzzzzzzzzzzzzz-->
        </div>
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navigation-example">
          <ul class="nav navbar-nav navbar-right">
            
            <li>
              <%= link_to( raw(("<i class='material-icons' >explore</i>  ") + (' Bares')), home_lugares_path, class:"btn btn-simple", target:"_blank") %>
            </li>
            <li>
              <%= link_to( raw(("<i class='fa fa-cart-plus' ></i> ") + (' Tienda')), home_tienda_path, class:"btn btn-simple", target:"_blank") %>
              
            </a>
          </li>
          <!--
          <li>
            <a href="https://www.instagram.com/CreativeTimOfficial" target="_blank" class="btn btn-simple">
              
              <i class="fa fa-map-signs"></i> Salir
            </a>
          </li>
          -->
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="navigation-example">
        
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to(raw(("<i class='fa fa-diamond' style='font-size:16px;'></i>") + (' Registrarse')), new_user_registration_path, class:"btn btn-danger btn-raised btn-lg" )  %>
          </li>
        </ul>
      </div>
      <% end %>
      
      
    </div>
  </nav>
  <!------------------YIELD---------------------------->
  <%= yield %>
</body>
</html>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>